
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
